site_name: Aplicaciones Web
site_url: https://atorrescode.github.io/aw/
theme:
   name: 'material'
   features:
    - navigation.sections
    - navigation.top
    - content.code.copy
   font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'
   icon:
    repo: 'fontawesome/brands/github'
   palette:
    - scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

    - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar
   logo: assets/img/favicon.ico
   favicon: assets/img/favicon.ico

nav:
    - Home: index.md
    - Unidad 1. Aplicaciones web de escritorio:
      - 1. Internet, la Web y sus aplicaciones: u01-aplicaciones-web-escritorio/r01-internet-y-web.md
      - 2. Conceptos básicos de Internet: u01-aplicaciones-web-escritorio/r02-conceptos-basicos-internet.md
      - Actividades Office 365: u01-aplicaciones-web-escritorio/a01-office365.md
      - Actividades Microsoft Sway: u01-aplicaciones-web-escritorio/a02-sway.md
      - Actividades Navegando con Google: u01-aplicaciones-web-escritorio/a03-busquedas-google.md
      - Actividades OneDrive y ofimática online: u01-aplicaciones-web-escritorio/a04-onedrive-ofimatica-online.md
extra_css:
  - assets/css/style.css
extra_templates:
plugins:
  - search
  # - with-pdf
  # - pdf-export:
  #     combined: true
  # - page-to-pdf
markdown_extensions:
  # Avisos: !!! note, !!! warning, !!! tip...
  - admonition

  # Bloques desplegables: ??? question, ???+ example...
  - pymdownx.details

  # Resaltado de código
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true

  # Bloques de código avanzados y Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Listas de tareas: - [ ] y - [x]
  - pymdownx.tasklist:
      custom_checkbox: true

  # Permite añadir atributos a elementos Markdown
  - attr_list

  # Permite combinar Markdown dentro de HTML
  - md_in_html

  # Notas al pie
  - footnotes